import argparse
import re
import urllib.request
from datetime import datetime
import os.path

parser = argparse.ArgumentParser(description='Betaflight configuration converter')
parser.add_argument('--name', help='Betaflight target name (ex: FLYWOOF722PROV2)', type=str, required=True)
args = parser.parse_args()

# get the original betaflight target config file
with urllib.request.urlopen(f'https://raw.githubusercontent.com/betaflight/config/refs/heads/master/configs/{args.name}/config.h') as bf_config_req:
    bf_config = bf_config_req.read().decode().strip().split('\n')

# parse keys and values
new_values = {}
for i, line in enumerate(bf_config):
    # parses KEY and VALUE in #define KEY VALUE
    val = re.findall(r'(?:\#\bdefine (\w*)? +?\b)(\w*)?', line)
    if not val:  # not a correct line
        continue
    key, value = val[0]
    new_values[key] = value

# get the template configuration
with open('template.h', 'r') as template_file:
    template = template_file.read().strip().split('\n')

for i, line in enumerate(template):
    # get the placeholder name ($VAR)
    template_var = re.findall(r'(?:\#\bdefine(?: \w*)? \$\b)(\w*)', line)
    if not template_var:  # no placeholder on this line
        continue
    template_var = template_var[0]
    new_value = '-1 // ' + template_var  # default value, in case no replacement was found
    if template_var in new_values.keys():  # get the replacement value
        print(f'found {template_var}: {new_values[template_var]}')
        new_value = new_values[template_var]
        if 'INSTANCE' in template_var:  # only keep the number (I2CDEV_1 => 1)
            new_value = new_value[-1]
    else:
        print(f'no value found for {template_var}')
    template[i] = line.replace(f'${template_var}', new_value)  # replace the line with the new value

# write the output
with open(f'{args.name}.h', 'w') as output:
    output.write('\n'.join(template))
    output.write(f'\n\n// generated by BNP {os.path.basename(__file__)} on {datetime.today()}')

